name: Checks the latex of the thesis
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the dependencies
        run: make setup

      - name: Run the checks
        run: make lint
